inherit_from: .rubocop_todo.yml

require:
  - rubocop-rspec
  - rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2.2

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false